name: Create release executables

on: workflow_dispatch

env:
  TARGET: webcam_info-tests


jobs:
#-----------------------------------------------------------------------------------------------
  Windows_Clang_Release:
    name: Windows Clang Release
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/tests -B ${{github.workspace}}\build -T ClangCL 

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config Debug --target ${{env.TARGET}}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/webcam_info-tests
        
#-----------------------------------------------------------------------------------------------
  Linux_Clang_Release:
    name: Linux Clang Release
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update apt-get
      run: sudo apt-get update -y

    - name: Install glfw dependencies
      run: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-common-dev build-essential libgtk-3-dev    
 
    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/tests -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=Debug -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ 

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug --target ${{env.TARGET}}

    - name: Rename
      run: |
            mv ${{github.workspace}}/build/webcam_info-tests ${{github.workspace}}/build/webcam_info-tests-linux

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{github.workspace}}/build/webcam_info-tests

#-----------------------------------------------------------------------------------------------
  MacOS_Clang_Release:
    name: MacOS Clang Release
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/tests -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=Debug -D CMAKE_C_COMPILER=$(brew --prefix llvm@15)/bin/clang -D CMAKE_CXX_COMPILER=$(brew --prefix llvm@15)/bin/clang++

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug --target ${{env.TARGET}}

    - name: Rename
      run: |
            mv ${{github.workspace}}/build/webcam_info-tests ${{github.workspace}}/build/webcam_info-tests-macos

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{github.workspace}}/bin/webcam_info-tests

